version: "2.1"

services:
  ping-monitoring:
    build: ping-monitoring
  wifi-monitoring:
    build: wifi-monitoring
#    network_mode: host
#    privileged: true
#    cap_add:
#      - NET_ADMIN
#      - ALL
