FROM balenalib/raspberry-pi-alpine-golang:latest-build AS build

WORKDIR /go/src/github.com/mjasion/balena-monitoring

COPY . /go/src/github.com/mjasion/balena-monitoring

RUN go build .

FROM balenalib/raspberry-pi-alpine:3.13

WORKDIR /go/src/github.com/mjasion/balena-monitoring
COPY --from=build /go/src/github.com/mjasion/balena-monitoring .

CMD ./balena-monitoring
