version: "2.1"

services:
  hellpot:
    build: hellpot
    ports:
      - "8080:8080"
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNGJlMzc2Mjk5ZWE2ZjM4MDRkNmI4OWQ2NjFkMmUzMGEiLCJ0IjoiYTQ3ZDUyYjktYzg2ZS00NTM1LThmNTctMmM5M2I5NjZkYTA4IiwicyI6Ik9XWmhNalEzTmpVdE1XRm1OUzAwWkRnMExUa3dOVGN0TmpGa09HRTNNell6WmpBMiJ9
  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
  wolweb:
    build: wolweb
    network_mode: host

    # Use environment variable below to change port or virtual directory.
    environment:
      WOLWEBHOST: "0.0.0.0"
      WOLWEBPORT: "8089"
      #WOLWEBVDIR: "/wolweb"
      WOLWEBBCASTIP: "192.168.1.255:9"
