version: "2.1"

services:
  ping-monitoring:
    build: ping-monitoring
  cloudflare-ddns:
    build: cloudflare-ddns
  nginx:
    build: nginx
    ports:
      - "8080:8080"
#      - "80:8080"
      - "8443:8443"
#      - "443:8443"
