version: "2.1"

services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
  wolweb:
    build: wolweb
    network_mode: host

    # Use environment variable below to change port or virtual directory.
    environment:
      WOLWEBHOST: "0.0.0.0"
      WOLWEBPORT: "8089"
      #WOLWEBVDIR: "/wolweb"
      WOLWEBBCASTIP: "192.168.1.255:9"
  pstryk_metric:
    build: pstryk_metric
    network_mode: host

