FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-golang:latest-build AS build

WORKDIR /go/src/github.com/mjasion/balena-chelm

COPY . /go/src/github.com/mjasion/balena-chelm

RUN go build .

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.13
WORKDIR /go/src/github.com/mjasion/balena-chelm
COPY --from=build /go/src/github.com/mjasion/balena-chelm .

CMD ./balena-chelm