# BLE Temperature Monitoring Configuration

# BLE scanning interval in seconds (minimum: 1)
scanIntervalSeconds: 60

# List of sensor MAC addresses to monitor
# Format: XX:XX:XX:XX:XX:XX (case insensitive)
sensors:
  - "A4:C1:38:00:00:01"  # Replace with your sensor MAC
  - "A4:C1:38:00:00:02"  # Replace with your sensor MAC
  - "A4:C1:38:00:00:03"  # Replace with your sensor MAC
  - "A4:C1:38:00:00:04"  # Replace with your sensor MAC

# How often to push metrics to Prometheus (in seconds)
pushIntervalSeconds: 15

# Prometheus remote_write endpoint URL
# For Grafana Cloud, use: https://prometheus-prod-XX-YY-ZZ.grafana.net/api/prom/push
prometheusUrl: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"

# Prometheus basic auth username (Grafana Cloud instance ID)
prometheusUsername: "123456"

# Prometheus basic auth password (Grafana Cloud API key)
# IMPORTANT: Use environment variable PROMETHEUS_PASSWORD for production
prometheusPassword: ""

# Name of the metric to create in Prometheus
metricName: "ble_temperature_celsius"

# Whether to start pushing at even second boundaries (improves alignment in time series)
startAtEvenSecond: true

# Ring buffer capacity (number of readings to buffer before push)
bufferCapacity: 1000

# Health check HTTP server port
healthCheckPort: 8080

# Logging configuration
# Format: "json" for structured JSON logging, "console" for human-readable output
logFormat: "console"
# Level: "debug", "info", "warn", or "error"
logLevel: "info"
