# BLE Temperature Monitoring Configuration

# BLE scanning configuration
ble:
  # Interval between scan cycles in seconds (minimum: 1)
  scanIntervalSeconds: 60

  # List of sensor MAC addresses to monitor
  # Format: XX:XX:XX:XX:XX:XX (case insensitive)
  sensors:
    - A4:C1:38:ED:C0:21   # Sypialnia
    - A4:C1:38:26:E2:4C   # Salon

# Prometheus metrics push configuration
prometheus:
  # Interval between metric pushes in seconds (minimum: 1)
  pushIntervalSeconds: 15

  # Prometheus remote_write endpoint URL
  # For Grafana Cloud, use: https://prometheus-prod-XX-YY-ZZ.grafana.net/api/prom/push
  prometheusUrl: "https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push"

  # Prometheus basic auth username (Grafana Cloud instance ID)
  prometheusUsername: "83165"

  # Grafana Cloud password (API key)
  # IMPORTANT: Use PROMETHEUS_PASSWORD environment variable instead of storing here
  prometheusPassword: ""

  # Prometheus metric name
  metricName: "ble_temperature_celsius"

  # Start pushing at even second boundaries (improves alignment in time series)
  startAtEvenSecond: true

  # Ring buffer size (number of readings to buffer before push)
  bufferSize: 1000

# Logging configuration
logging:
  # Log format: "console" (human-readable) or "json" (structured)
  # Use "console" for development, "json" for production
  logFormat: "console"

  # Log level: "debug", "info", "warn", "error"
  logLevel: "info"
