name: BalenaCloud Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2.4.0
    - name: Balena Deploy
      uses: bekriebel/balena-cli-action@v1
      if: success()
      with:
        balena_api_token: ${{secrets.BALENA_API_TOKEN}}
        balena_command: "balena deploy ${{ secrets.BALENA_APP_NAME }}"

