name: BalenaCloud Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v1.1.0
    - name: Balena Push
      uses: theaccordance/balena-push@v1.0.0
      with:
        # API Key to interact with BalenaCloud
        api-token: ${{ secrets.BALENA_API_TOKEN }} 
        # name of the BalenaCloud application
        application-name: ${{ secrets.BALENA_APP_NAME }}
        # Optional. Provide a subfolder path, example: ./balena-wpe
        application-path: .
