name: BalenaCloud Deploy
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 9 1 * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup NodeJS
      uses: actions/setup-node@v5
    - name: Balena Deploy
      uses: mjasion/balena-cli-action@master
      if: success()
      with:
        balena_api_token: ${{secrets.BALENA_API_TOKEN}}
        balena_command: "push ${{ secrets.BALENA_APP_NAME }}"

