name: Pstryk Metric Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'pstryk_metric/**'
      - '.github/workflows/pstryk-metric-test.yml'
  push:
    branches-ignore:
      - main
    paths:
      - 'pstryk_metric/**'
      - '.github/workflows/pstryk-metric-test.yml'

concurrency:
  group: pstryk-metric-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pstryk_metric

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.3'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Generate coverage report
      run: go tool cover -func=coverage.out

    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v5
      with:
        name: coverage-report
        path: pstryk_metric/coverage.out

    - name: Display coverage summary
      run: |
        echo "### Coverage Summary" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        go tool cover -func=coverage.out >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
