name: Secret Scanning

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    # Run weekly on Fridays at 10 AM UTC
    - cron: '0 10 * * 5'
  workflow_dispatch:

concurrency:
  group: secret-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trufflehog:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history for comprehensive scanning

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --only-verified --fail

  gitleaks:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  detect-secrets:
    name: Detect Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Run detect-secrets
        run: |
          detect-secrets scan --all-files --force-use-all-plugins \
            --exclude-files '.git/.*' \
            --exclude-files '.*\.lock' \
            --exclude-files 'go\.sum' > .secrets.baseline || true

          if [ -s .secrets.baseline ]; then
            echo "Potential secrets detected!"
            cat .secrets.baseline
            exit 1
          fi
          echo "No secrets detected"

  trivy-secret-scan:
    name: Trivy Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Trivy secret scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'secret'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM'

  summary:
    name: Scan Summary
    runs-on: ubuntu-latest
    needs: [trufflehog, gitleaks, detect-secrets, trivy-secret-scan]
    if: always()
    steps:
      - name: Check scan results
        run: |
          echo "Secret scanning completed"
          echo "TruffleHog: ${{ needs.trufflehog.result }}"
          echo "Gitleaks: ${{ needs.gitleaks.result }}"
          echo "Detect Secrets: ${{ needs.detect-secrets.result }}"
          echo "Trivy: ${{ needs.trivy-secret-scan.result }}"

          if [[ "${{ needs.trufflehog.result }}" == "failure" ]] || \
             [[ "${{ needs.gitleaks.result }}" == "failure" ]] || \
             [[ "${{ needs.detect-secrets.result }}" == "failure" ]] || \
             [[ "${{ needs.trivy-secret-scan.result }}" == "failure" ]]; then
            echo "⚠️ Secret scanning detected issues"
            exit 1
          fi

          echo "✅ All secret scans passed"
