FROM balenalib/raspberry-pi-alpine-golang:1.18-3.15-build-20221215 AS build

WORKDIR /go/src/github.com/mjasion/ping-monitoring

COPY . /go/src/github.com/mjasion/ping-monitoring

RUN go build .

FROM balenalib/raspberry-pi-alpine:3.17-20221215

COPY --from=build /go/src/github.com/mjasion/ping-monitoring/ping-monitoring .

CMD ./ping-monitoring
